# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:lsER2i8UTgSVwGLulyTwq2Iz3tmuF68qFqmNyhqLCgc=,iv:W+nDxQGaW2O5eRvXow7oKZWQbMRgqLsrauoCRjoiy1U=,tag:sfhqOAKMCxTuvG+1v5v6Ew==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYlFEbkhYR1d3WEl0S3Yw
        RVNKb1AvUS9POFJHclQ4QmRGNEd5Sk5tOVNJCjN1VlRxZG0vTEhRU2hqQXlWUXZv
        YWREd2UxWmQxUSthbmFhVk95VWZHU0kKLS0tIDhkVG9HajNyaWF0dDdOWTVVVmFY
        MkZGbm5iY1orNU50bHBQUm8rMHlPeFkK6LkH8lL9ltthTa8VoJkAJim1VoWJjBh3
        XEdN1u1xfmn+y8Iw5oX5lTdUuaB9JUTnoLuixlURxTo6GCO+ANb5Lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T11:47:21Z"
  mac: ENC[AES256_GCM,data:zA2QnNR5f57sZwO+sLhcZRUu6jK3Q/MEJbB5Kur1ixZUtSiVpUUJpJhwsZqk051eTkZoCjpJ9QWukA6EDKBYtggewqhL8twtBHcnObPzHSVdNOLWmLR+uG0BFChwQc99b4ujguz4WCP0RcatDC+secO7WubWsqCowr4nenzzdhQ=,iv:Gs56tnb4aT4Jc0vV/+oKHCGAEh4t7XKj6tBprtRKeO8=,tag:Z/1PFNnJINsgQDJKE0Xl7Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
