apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_EXAMPLE: ENC[AES256_GCM,data:IHkwKV6g0O5Ovgd/vnSRdK+kPHn0wAamODp0q74TohPEkEfcG7mwHvqRO9bC+eLUnCfG2l/TkO/nGGFn/Q/bam/9iigZlLc=,iv:YFaeWQYp7Eal12f1LqivK2/TiJUlVnLz29RSdrG5MXA=,tag:aqOvKXRn4t8ivFqGibsygg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b2QyUS9TZW44Mlg0L0xM
        aGdhUmNWeHRuUWVlcS9sT2xiQmNJc0NWV1dzCmhqSjZsdlNqTCtpYjIzVk9FdVR1
        aU0rUUVvN3czaUNtV0VJNGxiOFY3OFkKLS0tIC9meGdNK2F2WUxOTmtUekZNYXVq
        NGgwVjVRZGxJNTFTcUh1N2xqV1JPbWsKeRBizZqh3sjIZkDgEpOsp1GkEtm8jL0W
        nTXrgYuzyhlsGnFF70z1fiMLTWPqOrMH+HojKvyy8fIt7rXypqu7hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T11:27:36Z"
  mac: ENC[AES256_GCM,data:LaYdGZ+OcVY36crU7Kz8STMVaijPRBnORivfJ/qXB62KNBh+eDWOP5UIdJDWixXgVHby+IU5GgFe3+D7TCOfCMCQ+kKQQG8F7MHmh0tudousurg6M3PdUPtnX6lawxkECLzgVc/qpkk+XOxJy5f/4ZvrSmyVfmGCwg+XLfqUE+4=,iv:ryn3+DvEgMY6BbsslwbPsalIsejwL8i+hpUMAGNKXBo=,tag:Vuv51F49I6esYtCmtezAXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
