apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:UBui/w0ebGmY4ZmPhG3/7zG+aozLWkYPeQLvCeI37bUJgHylcaPW+4YoeTRP11WnL/7Yd7ItCLCEizkS4Bb7nKCt2pgXGVsTitMy,iv:QEjHDIEVNpUZAufEkrMasNdKvJynQ6s5mjz4A4VbOOc=,tag:uH5fc54yuol8Xdq1vAFPHQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYU5KU3ZhbVpSVkhtenBH
        WXhBT2JKU1FiRldjWVU3MDlyQVlOWjNReGtVCkp4aW5MRlM4Sk9pYjFlZE9BUkE0
        b1R1UFh4eFpwN3M2bWVhWVN1czYvLzQKLS0tIGpGYXZuN0FoK3hZdkRrMS9qV0RL
        b2NNOGVKV3Rmbnkrbkowa045dkFrZkkKnmkkz87aT5j3cLVnlmrMmIPEnrOrBYAQ
        J1CwN0iNBSYtEwVh0oLqMMpoz6cl+1PbUo4El02oC/RGaJzfl48Bjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T11:27:36Z"
  mac: ENC[AES256_GCM,data:iyuaZ+xhdzX0pupG6lAlSZyb1bzdCCGk6AgXO6y3rGMHonYAdiJdvVNLnB1ZI9c4GHZ/Zfp9RaCEVLrjDbbg/1URh7MqbLqn3AZxVEnlt87IkH3KXJlWX3al1m4YBIlvF4FjzOzn6ZQDClKKYdeOwqK83C+C4gFP3YVHXQ+p3fQ=,iv:CCUcHWChA6bA6LBmi2DuNh3HEjCc5z5nl915K9Wahao=,tag:14R5c689kywKBjKjj+sY6Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
